### ISSUE TITLE
GUI freezes when running a config file

### ISSUE THREAD

**Issue by parisaSHAFIEI** [groops-devs/groops#32] opened 2022-02-15 16:15 UTC
Dear developers, 

First of all, I would like to appreciate all the members involved in GROOPS project. In fact, it is an immensely powerful software.

I have followed all the steps in the installation page and installed GROOPS on Windows. Actually, during the installation, I was so careful about the versions to not make any problem. However, while I am using the "Desktop Qt 5.15.1 MinGW 64 bit" kit to build the groopsGui.pro, I get into trouble. It should be noted that it builds the project and opens the GROOPS GUI, but I cannot run any of the configuration files and groopsGui freezes. 

I have tried a lot and reinstalled the software for several times, but I could not solve the problem. Then, I would be pleased if you could tell me what I should do so as to fix the problem. 

Thank you in advance for your cooperation and support

Best regards, 
Parisa SHAFIEI

**Comment by parisaSHAFIEI** [comment] 2022-02-15 17:19
Hello Sebastian, 

Thank you for your reply. 

I think I explained it a little bit bad that made it hard for you to understand the nature of the issue. In fact, when I opened the “groopsGui.pro” in Qt and build project, it opens the groopsGui window in which I can write and open config files and also I can edit them. However, to pinpoint the issue, I must add that when I want to run any of those config files, it freezes and I can do nothing with the software (please see the attached picture). 

Additionally, regarding your recommendation, there are two important issues:

1-When I call the groopsGui.exe in the command window, the groopsGui window appears, but when I want to run any config file, it freezes!

2- I called the “groops.exe 01ConvertSatelliteData106.xml” in the command window, it processed all the data successfully (please see the attached picture).

All things considered, I deem that problem arises in GUI when it freezes. 

Best regards, 
Parisa

![GROOPS-2](https://user-images.githubusercontent.com/99748448/154114566-8ba02960-51f0-416e-83fa-e15c17637405.PNG)
![GROOPS-3](https://user-images.githubusercontent.com/99748448/154114570-1222547a-0a2c-42c3-948c-f89f8826e746.PNG)
![GUI](https://user-images.githubusercontent.com/99748448/154114574-265f8058-dad6-4384-b010-3366389daba3.PNG)
![Qt](https://user-images.githubusercontent.com/99748448/154114622-0074fa3c-2008-4108-84d1-07110b6cc3ca.jpeg)

**Comment by sestras** [comment] 2022-02-16 09:38
Have you tried installing the GUI from our [precompiled binaries](https://github.com/groops-devs/groops/releases/download/2021-09-06/groopsGui-2021-09-06-win64.exe) instead of compiling it yourself as I suggested in my reply above? (I edited that part in shortly after my initial reply because I forgot about it, so you might have missed it.) Does the problem still arise with that version of the GUI?

Otherwise, we've determined that you can open and edit config files in the GUI and are able to run GROOPS via the command line. What the GUI does when you try to run a script directly from it is very similar, in that it calls a predefined command. In case of Windows it is "cd /d %w && groops.exe %f". This means what should happen is that a command windows is opened, it changes the directory  (%w) and calls groops.exe with the selected config file (%f).

To narrow down the issue further, could you please try to add a new run command via the Settings - Commands dialog like this:
![commands](https://user-images.githubusercontent.com/9025982/154236017-d51d986b-635f-4572-907d-fa15377bc87d.png)
and then select that command in the run dialog like this:
![run](https://user-images.githubusercontent.com/9025982/154236137-8f924a9c-a87c-4941-8c28-507ab2d12277.png)
If you then run the script using this command, instead of running the GROOPS config file, the GUI should just open a command window passing "echo test", meaning it should show "test" as an output in the window. Does that work or does it also freeze in this case?

**Comment by sestras** [comment] 2022-02-16 13:50
Ok, so the issue is that the GUI freezes when the run dialog window is supposed to open. Interestingly, you don't seem to have an issue opening the Settings - Commands dialog window, as you were able to add the test command. From a code perspective, both of these dialogs work the same, so I don't understand why one works and the other doesn't.

Can you please try a few other things, just to make sure:

1. Once the GUI freezes, try pressing the Esc key and see if the GUI becomes unfrozen again. The run dialog takes away the focus from the main window and it might appear as frozen because of that. Pressing Esc should close the run dialog.
2. Please check that the run dialog does not somehow open on a different screen (in case you use multiple monitors). Try pressing Windows key + arrow keys to see if you can move the dialog between screens. 
3. The size and position of the run dialog is saved in the registry. Maybe somehow invalid values got saved there, which is why you can't see the dialog window. You can type "regedit" in the Windows start menu to open the Registry Editor. Go to Computer\HKEY_CURRENT_USER\SOFTWARE\groops-devs\groopsGui\executeDialog and check the two keys for position and size on the right side. Close the GUI, delete both of them using right click - Delete, and reopen the GUI. This should reset the position and size of the run dialog.

**Comment by parisaSHAFIEI** [comment] 2022-02-16 14:21
Dear Sebastian,

Good news!

Now, GROOPS GUI is working properly and it does not freeze. Here is some information that I would like to add for the other individuals who may have the same issue on their system:

1- By pressing the Esc button, the GUI became unfrozen again. 

2- My colleague checked the second point on his computer and by pressing the Windows key + arrow keys, he could move the "Execute dialog" between screens.

3- And finally, this point solved my problem. I deleted both of them in "regedit" and reopened the GUI and I noticed that the issue has been solved.   

So, I am really grateful to you because of the time you spent on answering my question and helping me to resolve the issue. Your consideration is really appreciated. 

Best regards, 
Parisa 

![Execute Window](https://user-images.githubusercontent.com/99748448/154284010-010275bd-4fc0-4101-9c3c-da68a2cb2769.PNG)

**Comment by sestras** [comment] 2022-02-16 15:46
That's great to hear and I'm glad I could help!

To summarize, what probably happened is that somehow your run dialog window got moved somewhere off-screen so you were not able to see it. As the dialog remembers its position for user convenience, it then always opened in this location and it appeared as if the GUI had frozen. 

As I have no idea how this happened in the first place, I can't think of a good way to prevent it right now. I'll look into it in case more people run into a similar problem, but for now I'll close this issue.

**Closed by sestras** 2022-02-16 15:46 UTC
